# Generated by Django 6.0.3 on 2026-03-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbTabelaAtendimento',
            fields=[
                ('ATE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ATE_NOME', models.CharField(max_length=250)),
                ('ATE_TELEFONE', models.CharField(max_length=20)),
                ('ATE_INTERESSE', models.CharField(max_length=10)),
                ('ATE_MENSSAGEM', models.CharField(max_length=250)),
                ('ATE_DATCADASTRO', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TBTABELA_ATENDIMENTO',
            },
        ),
    ]
