services:
  db:
    image: mysql:8.4
    container_name: elleva_mysql
    environment:
      # O Docker vai ler as variáveis que você já tem no seu .env
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      # Isso garante que se você desligar o PC, os dados do banco não se percam
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: elleva_web
    volumes:
      # Mapeia a pasta do seu PC para dentro do container (atualiza em tempo real)
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Aqui substituímos o 127.0.0.1 pelo nome do container 'db'
      # para que o Django saiba como achar o MySQL dentro da rede do Docker
      - DB_HOST=db
    depends_on:
      - db

volumes:
  mysql_data:
